# Generated by Django 3.0.7 on 2020-10-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('mess', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('add', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('genral-physician', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dramatologist', 'Dramatologist'), ('neurologist', 'Neurologist'), ('physciotherpist', 'Physciotherpist'), ('dentist', 'Dentist')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=12)),
                ('l_name', models.CharField(max_length=12)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('add', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('day', models.CharField(max_length=30)),
                ('timeslot', models.CharField(max_length=30)),
                ('symptom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Doctor')),
            ],
        ),
    ]
