# Generated by Django 3.0.7 on 2020-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201007_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='phone1',
            field=models.IntegerField(null=True),
        ),
    ]
