# Generated by Django 3.1.3 on 2020-11-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201108_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='phone2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
